<?php
/**
 * AdminApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Morent.WebApi | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\apis;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * AdminApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdminApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiAdminCarCarIdImagesImageIdPost' => [
            'application/json',
        ],
        'apiAdminCarCarIdImagesImageIdSetPrimaryPut' => [
            'application/json',
        ],
        'apiAdminCarCarIdImagesPost' => [
            'application/x-www-form-urlencoded',
        ],
        'apiAdminCarCarIdImagesReorderPut' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'apiAdminCarIdDelete' => [
            'application/json',
        ],
        'apiAdminCarIdPut' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'apiAdminCarPost' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdPost
     *
     * @param  string $car_id car_id (required)
     * @param  string $image_id image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiAdminCarCarIdImagesImageIdPost($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdPost'][0])
    {
        $this->apiAdminCarCarIdImagesImageIdPostWithHttpInfo($car_id, $image_id, $contentType);
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdPostWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiAdminCarCarIdImagesImageIdPostWithHttpInfo($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdPost'][0])
    {
        $request = $this->apiAdminCarCarIdImagesImageIdPostRequest($car_id, $image_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdPostAsync
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesImageIdPostAsync($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdPost'][0])
    {
        return $this->apiAdminCarCarIdImagesImageIdPostAsyncWithHttpInfo($car_id, $image_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdPostAsyncWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesImageIdPostAsyncWithHttpInfo($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdPost'][0])
    {
        $returnType = '';
        $request = $this->apiAdminCarCarIdImagesImageIdPostRequest($car_id, $image_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiAdminCarCarIdImagesImageIdPost'
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiAdminCarCarIdImagesImageIdPostRequest($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdPost'][0])
    {

        // verify the required parameter 'car_id' is set
        if ($car_id === null || (is_array($car_id) && count($car_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $car_id when calling apiAdminCarCarIdImagesImageIdPost'
            );
        }

        // verify the required parameter 'image_id' is set
        if ($image_id === null || (is_array($image_id) && count($image_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $image_id when calling apiAdminCarCarIdImagesImageIdPost'
            );
        }


        $resourcePath = '/api/admin/car/{carId}/images/{imageId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($car_id !== null) {
            $resourcePath = str_replace(
                '{' . 'carId' . '}',
                ObjectSerializer::toPathValue($car_id),
                $resourcePath
            );
        }
        // path params
        if ($image_id !== null) {
            $resourcePath = str_replace(
                '{' . 'imageId' . '}',
                ObjectSerializer::toPathValue($image_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdSetPrimaryPut
     *
     * @param  string $car_id car_id (required)
     * @param  string $image_id image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\models\CarImageDto|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails
     */
    public function apiAdminCarCarIdImagesImageIdSetPrimaryPut($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'][0])
    {
        list($response) = $this->apiAdminCarCarIdImagesImageIdSetPrimaryPutWithHttpInfo($car_id, $image_id, $contentType);
        return $response;
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdSetPrimaryPutWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\models\CarImageDto|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiAdminCarCarIdImagesImageIdSetPrimaryPutWithHttpInfo($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'][0])
    {
        $request = $this->apiAdminCarCarIdImagesImageIdSetPrimaryPutRequest($car_id, $image_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\CarImageDto',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ProblemDetails',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\models\CarImageDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\CarImageDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdSetPrimaryPutAsync
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesImageIdSetPrimaryPutAsync($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'][0])
    {
        return $this->apiAdminCarCarIdImagesImageIdSetPrimaryPutAsyncWithHttpInfo($car_id, $image_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiAdminCarCarIdImagesImageIdSetPrimaryPutAsyncWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesImageIdSetPrimaryPutAsyncWithHttpInfo($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'][0])
    {
        $returnType = '\OpenAPI\Client\models\CarImageDto';
        $request = $this->apiAdminCarCarIdImagesImageIdSetPrimaryPutRequest($car_id, $image_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiAdminCarCarIdImagesImageIdSetPrimaryPut'
     *
     * @param  string $car_id (required)
     * @param  string $image_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiAdminCarCarIdImagesImageIdSetPrimaryPutRequest($car_id, $image_id, string $contentType = self::contentTypes['apiAdminCarCarIdImagesImageIdSetPrimaryPut'][0])
    {

        // verify the required parameter 'car_id' is set
        if ($car_id === null || (is_array($car_id) && count($car_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $car_id when calling apiAdminCarCarIdImagesImageIdSetPrimaryPut'
            );
        }

        // verify the required parameter 'image_id' is set
        if ($image_id === null || (is_array($image_id) && count($image_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $image_id when calling apiAdminCarCarIdImagesImageIdSetPrimaryPut'
            );
        }


        $resourcePath = '/api/admin/car/{carId}/images/{imageId}/set-primary';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($car_id !== null) {
            $resourcePath = str_replace(
                '{' . 'carId' . '}',
                ObjectSerializer::toPathValue($car_id),
                $resourcePath
            );
        }
        // path params
        if ($image_id !== null) {
            $resourcePath = str_replace(
                '{' . 'imageId' . '}',
                ObjectSerializer::toPathValue($image_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiAdminCarCarIdImagesPost
     *
     * @param  string $car_id car_id (required)
     * @param  \SplFileObject|null $image image (optional)
     * @param  string|null $image_url image_url (optional)
     * @param  bool|null $set_as_primary set_as_primary (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\models\CarImageDto|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails
     */
    public function apiAdminCarCarIdImagesPost($car_id, $image = null, $image_url = null, $set_as_primary = null, string $contentType = self::contentTypes['apiAdminCarCarIdImagesPost'][0])
    {
        list($response) = $this->apiAdminCarCarIdImagesPostWithHttpInfo($car_id, $image, $image_url, $set_as_primary, $contentType);
        return $response;
    }

    /**
     * Operation apiAdminCarCarIdImagesPostWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  \SplFileObject|null $image (optional)
     * @param  string|null $image_url (optional)
     * @param  bool|null $set_as_primary (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\models\CarImageDto|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails|\OpenAPI\Client\models\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiAdminCarCarIdImagesPostWithHttpInfo($car_id, $image = null, $image_url = null, $set_as_primary = null, string $contentType = self::contentTypes['apiAdminCarCarIdImagesPost'][0])
    {
        $request = $this->apiAdminCarCarIdImagesPostRequest($car_id, $image, $image_url, $set_as_primary, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\CarImageDto',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ProblemDetails',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\models\CarImageDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\CarImageDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiAdminCarCarIdImagesPostAsync
     *
     * @param  string $car_id (required)
     * @param  \SplFileObject|null $image (optional)
     * @param  string|null $image_url (optional)
     * @param  bool|null $set_as_primary (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesPostAsync($car_id, $image = null, $image_url = null, $set_as_primary = null, string $contentType = self::contentTypes['apiAdminCarCarIdImagesPost'][0])
    {
        return $this->apiAdminCarCarIdImagesPostAsyncWithHttpInfo($car_id, $image, $image_url, $set_as_primary, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiAdminCarCarIdImagesPostAsyncWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  \SplFileObject|null $image (optional)
     * @param  string|null $image_url (optional)
     * @param  bool|null $set_as_primary (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesPostAsyncWithHttpInfo($car_id, $image = null, $image_url = null, $set_as_primary = null, string $contentType = self::contentTypes['apiAdminCarCarIdImagesPost'][0])
    {
        $returnType = '\OpenAPI\Client\models\CarImageDto';
        $request = $this->apiAdminCarCarIdImagesPostRequest($car_id, $image, $image_url, $set_as_primary, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiAdminCarCarIdImagesPost'
     *
     * @param  string $car_id (required)
     * @param  \SplFileObject|null $image (optional)
     * @param  string|null $image_url (optional)
     * @param  bool|null $set_as_primary (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiAdminCarCarIdImagesPostRequest($car_id, $image = null, $image_url = null, $set_as_primary = null, string $contentType = self::contentTypes['apiAdminCarCarIdImagesPost'][0])
    {

        // verify the required parameter 'car_id' is set
        if ($car_id === null || (is_array($car_id) && count($car_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $car_id when calling apiAdminCarCarIdImagesPost'
            );
        }





        $resourcePath = '/api/admin/car/{carId}/images';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($car_id !== null) {
            $resourcePath = str_replace(
                '{' . 'carId' . '}',
                ObjectSerializer::toPathValue($car_id),
                $resourcePath
            );
        }

        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'image' => $image,
            'image_url' => $image_url,
            'set_as_primary' => $set_as_primary,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiAdminCarCarIdImagesReorderPut
     *
     * @param  string $car_id car_id (required)
     * @param  \OpenAPI\Client\models\CarImageOrderItem[] $car_image_order_item car_image_order_item (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesReorderPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiAdminCarCarIdImagesReorderPut($car_id, $car_image_order_item, string $contentType = self::contentTypes['apiAdminCarCarIdImagesReorderPut'][0])
    {
        $this->apiAdminCarCarIdImagesReorderPutWithHttpInfo($car_id, $car_image_order_item, $contentType);
    }

    /**
     * Operation apiAdminCarCarIdImagesReorderPutWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  \OpenAPI\Client\models\CarImageOrderItem[] $car_image_order_item (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesReorderPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiAdminCarCarIdImagesReorderPutWithHttpInfo($car_id, $car_image_order_item, string $contentType = self::contentTypes['apiAdminCarCarIdImagesReorderPut'][0])
    {
        $request = $this->apiAdminCarCarIdImagesReorderPutRequest($car_id, $car_image_order_item, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiAdminCarCarIdImagesReorderPutAsync
     *
     * @param  string $car_id (required)
     * @param  \OpenAPI\Client\models\CarImageOrderItem[] $car_image_order_item (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesReorderPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesReorderPutAsync($car_id, $car_image_order_item, string $contentType = self::contentTypes['apiAdminCarCarIdImagesReorderPut'][0])
    {
        return $this->apiAdminCarCarIdImagesReorderPutAsyncWithHttpInfo($car_id, $car_image_order_item, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiAdminCarCarIdImagesReorderPutAsyncWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  \OpenAPI\Client\models\CarImageOrderItem[] $car_image_order_item (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesReorderPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarCarIdImagesReorderPutAsyncWithHttpInfo($car_id, $car_image_order_item, string $contentType = self::contentTypes['apiAdminCarCarIdImagesReorderPut'][0])
    {
        $returnType = '';
        $request = $this->apiAdminCarCarIdImagesReorderPutRequest($car_id, $car_image_order_item, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiAdminCarCarIdImagesReorderPut'
     *
     * @param  string $car_id (required)
     * @param  \OpenAPI\Client\models\CarImageOrderItem[] $car_image_order_item (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarCarIdImagesReorderPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiAdminCarCarIdImagesReorderPutRequest($car_id, $car_image_order_item, string $contentType = self::contentTypes['apiAdminCarCarIdImagesReorderPut'][0])
    {

        // verify the required parameter 'car_id' is set
        if ($car_id === null || (is_array($car_id) && count($car_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $car_id when calling apiAdminCarCarIdImagesReorderPut'
            );
        }

        // verify the required parameter 'car_image_order_item' is set
        if ($car_image_order_item === null || (is_array($car_image_order_item) && count($car_image_order_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $car_image_order_item when calling apiAdminCarCarIdImagesReorderPut'
            );
        }


        $resourcePath = '/api/admin/car/{carId}/images/reorder';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($car_id !== null) {
            $resourcePath = str_replace(
                '{' . 'carId' . '}',
                ObjectSerializer::toPathValue($car_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($car_image_order_item)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($car_image_order_item));
            } else {
                $httpBody = $car_image_order_item;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiAdminCarIdDelete
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiAdminCarIdDelete($id, string $contentType = self::contentTypes['apiAdminCarIdDelete'][0])
    {
        $this->apiAdminCarIdDeleteWithHttpInfo($id, $contentType);
    }

    /**
     * Operation apiAdminCarIdDeleteWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiAdminCarIdDeleteWithHttpInfo($id, string $contentType = self::contentTypes['apiAdminCarIdDelete'][0])
    {
        $request = $this->apiAdminCarIdDeleteRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiAdminCarIdDeleteAsync
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarIdDeleteAsync($id, string $contentType = self::contentTypes['apiAdminCarIdDelete'][0])
    {
        return $this->apiAdminCarIdDeleteAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiAdminCarIdDeleteAsyncWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarIdDeleteAsyncWithHttpInfo($id, string $contentType = self::contentTypes['apiAdminCarIdDelete'][0])
    {
        $returnType = '';
        $request = $this->apiAdminCarIdDeleteRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiAdminCarIdDelete'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiAdminCarIdDeleteRequest($id, string $contentType = self::contentTypes['apiAdminCarIdDelete'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiAdminCarIdDelete'
            );
        }


        $resourcePath = '/api/admin/car/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiAdminCarIdPut
     *
     * @param  string $id id (required)
     * @param  \OpenAPI\Client\models\UpdateCarCommand $update_car_command update_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiAdminCarIdPut($id, $update_car_command, string $contentType = self::contentTypes['apiAdminCarIdPut'][0])
    {
        $this->apiAdminCarIdPutWithHttpInfo($id, $update_car_command, $contentType);
    }

    /**
     * Operation apiAdminCarIdPutWithHttpInfo
     *
     * @param  string $id (required)
     * @param  \OpenAPI\Client\models\UpdateCarCommand $update_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiAdminCarIdPutWithHttpInfo($id, $update_car_command, string $contentType = self::contentTypes['apiAdminCarIdPut'][0])
    {
        $request = $this->apiAdminCarIdPutRequest($id, $update_car_command, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiAdminCarIdPutAsync
     *
     * @param  string $id (required)
     * @param  \OpenAPI\Client\models\UpdateCarCommand $update_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarIdPutAsync($id, $update_car_command, string $contentType = self::contentTypes['apiAdminCarIdPut'][0])
    {
        return $this->apiAdminCarIdPutAsyncWithHttpInfo($id, $update_car_command, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiAdminCarIdPutAsyncWithHttpInfo
     *
     * @param  string $id (required)
     * @param  \OpenAPI\Client\models\UpdateCarCommand $update_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarIdPutAsyncWithHttpInfo($id, $update_car_command, string $contentType = self::contentTypes['apiAdminCarIdPut'][0])
    {
        $returnType = '';
        $request = $this->apiAdminCarIdPutRequest($id, $update_car_command, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiAdminCarIdPut'
     *
     * @param  string $id (required)
     * @param  \OpenAPI\Client\models\UpdateCarCommand $update_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiAdminCarIdPutRequest($id, $update_car_command, string $contentType = self::contentTypes['apiAdminCarIdPut'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiAdminCarIdPut'
            );
        }

        // verify the required parameter 'update_car_command' is set
        if ($update_car_command === null || (is_array($update_car_command) && count($update_car_command) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_car_command when calling apiAdminCarIdPut'
            );
        }


        $resourcePath = '/api/admin/car/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_car_command)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_car_command));
            } else {
                $httpBody = $update_car_command;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiAdminCarPost
     *
     * @param  \OpenAPI\Client\models\CreateCarCommand $create_car_command create_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiAdminCarPost($create_car_command, string $contentType = self::contentTypes['apiAdminCarPost'][0])
    {
        $this->apiAdminCarPostWithHttpInfo($create_car_command, $contentType);
    }

    /**
     * Operation apiAdminCarPostWithHttpInfo
     *
     * @param  \OpenAPI\Client\models\CreateCarCommand $create_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiAdminCarPostWithHttpInfo($create_car_command, string $contentType = self::contentTypes['apiAdminCarPost'][0])
    {
        $request = $this->apiAdminCarPostRequest($create_car_command, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiAdminCarPostAsync
     *
     * @param  \OpenAPI\Client\models\CreateCarCommand $create_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarPostAsync($create_car_command, string $contentType = self::contentTypes['apiAdminCarPost'][0])
    {
        return $this->apiAdminCarPostAsyncWithHttpInfo($create_car_command, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiAdminCarPostAsyncWithHttpInfo
     *
     * @param  \OpenAPI\Client\models\CreateCarCommand $create_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiAdminCarPostAsyncWithHttpInfo($create_car_command, string $contentType = self::contentTypes['apiAdminCarPost'][0])
    {
        $returnType = '';
        $request = $this->apiAdminCarPostRequest($create_car_command, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiAdminCarPost'
     *
     * @param  \OpenAPI\Client\models\CreateCarCommand $create_car_command (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiAdminCarPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiAdminCarPostRequest($create_car_command, string $contentType = self::contentTypes['apiAdminCarPost'][0])
    {

        // verify the required parameter 'create_car_command' is set
        if ($create_car_command === null || (is_array($create_car_command) && count($create_car_command) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_car_command when calling apiAdminCarPost'
            );
        }


        $resourcePath = '/api/admin/car';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_car_command)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_car_command));
            } else {
                $httpBody = $create_car_command;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
