<?php
/**
 * CarApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Morent.WebApi | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\apis;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * CarApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CarApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiCarsCarIdImagesGet' => [
            'application/json',
        ],
        'apiCarsGet' => [
            'application/json',
        ],
        'apiCarsIdGet' => [
            'application/json',
        ],
        'apiCarsIdReviewsGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiCarsCarIdImagesGet
     *
     * @param  string $car_id car_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsCarIdImagesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\models\CarImageDto[]|\OpenAPI\Client\models\ProblemDetails
     */
    public function apiCarsCarIdImagesGet($car_id, string $contentType = self::contentTypes['apiCarsCarIdImagesGet'][0])
    {
        list($response) = $this->apiCarsCarIdImagesGetWithHttpInfo($car_id, $contentType);
        return $response;
    }

    /**
     * Operation apiCarsCarIdImagesGetWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsCarIdImagesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\models\CarImageDto[]|\OpenAPI\Client\models\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiCarsCarIdImagesGetWithHttpInfo($car_id, string $contentType = self::contentTypes['apiCarsCarIdImagesGet'][0])
    {
        $request = $this->apiCarsCarIdImagesGetRequest($car_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\CarImageDto[]',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\models\CarImageDto[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\CarImageDto[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiCarsCarIdImagesGetAsync
     *
     * @param  string $car_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsCarIdImagesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsCarIdImagesGetAsync($car_id, string $contentType = self::contentTypes['apiCarsCarIdImagesGet'][0])
    {
        return $this->apiCarsCarIdImagesGetAsyncWithHttpInfo($car_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiCarsCarIdImagesGetAsyncWithHttpInfo
     *
     * @param  string $car_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsCarIdImagesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsCarIdImagesGetAsyncWithHttpInfo($car_id, string $contentType = self::contentTypes['apiCarsCarIdImagesGet'][0])
    {
        $returnType = '\OpenAPI\Client\models\CarImageDto[]';
        $request = $this->apiCarsCarIdImagesGetRequest($car_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiCarsCarIdImagesGet'
     *
     * @param  string $car_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsCarIdImagesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiCarsCarIdImagesGetRequest($car_id, string $contentType = self::contentTypes['apiCarsCarIdImagesGet'][0])
    {

        // verify the required parameter 'car_id' is set
        if ($car_id === null || (is_array($car_id) && count($car_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $car_id when calling apiCarsCarIdImagesGet'
            );
        }


        $resourcePath = '/api/cars/{carId}/images';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($car_id !== null) {
            $resourcePath = str_replace(
                '{' . 'carId' . '}',
                ObjectSerializer::toPathValue($car_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiCarsGet
     *
     * @param  string|null $car_filter_brand car_filter_brand (optional)
     * @param  string|null $car_filter_type car_filter_type (optional)
     * @param  int|null $car_filter_capacity car_filter_capacity (optional)
     * @param  string|null $car_filter_fuel_type car_filter_fuel_type (optional)
     * @param  string|null $car_filter_gearbox car_filter_gearbox (optional)
     * @param  float|null $car_filter_min_price car_filter_min_price (optional)
     * @param  float|null $car_filter_max_price car_filter_max_price (optional)
     * @param  int|null $car_filter_rating car_filter_rating (optional)
     * @param  string|null $car_filter_location car_filter_location (optional)
     * @param  string|null $car_filter_search car_filter_search (optional)
     * @param  string|null $car_filter_sort car_filter_sort (optional)
     * @param  int|null $paged_query_page paged_query_page (optional)
     * @param  int|null $paged_query_page_size paged_query_page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\models\CarDto[]
     */
    public function apiCarsGet($car_filter_brand = null, $car_filter_type = null, $car_filter_capacity = null, $car_filter_fuel_type = null, $car_filter_gearbox = null, $car_filter_min_price = null, $car_filter_max_price = null, $car_filter_rating = null, $car_filter_location = null, $car_filter_search = null, $car_filter_sort = null, $paged_query_page = null, $paged_query_page_size = null, string $contentType = self::contentTypes['apiCarsGet'][0])
    {
        list($response) = $this->apiCarsGetWithHttpInfo($car_filter_brand, $car_filter_type, $car_filter_capacity, $car_filter_fuel_type, $car_filter_gearbox, $car_filter_min_price, $car_filter_max_price, $car_filter_rating, $car_filter_location, $car_filter_search, $car_filter_sort, $paged_query_page, $paged_query_page_size, $contentType);
        return $response;
    }

    /**
     * Operation apiCarsGetWithHttpInfo
     *
     * @param  string|null $car_filter_brand (optional)
     * @param  string|null $car_filter_type (optional)
     * @param  int|null $car_filter_capacity (optional)
     * @param  string|null $car_filter_fuel_type (optional)
     * @param  string|null $car_filter_gearbox (optional)
     * @param  float|null $car_filter_min_price (optional)
     * @param  float|null $car_filter_max_price (optional)
     * @param  int|null $car_filter_rating (optional)
     * @param  string|null $car_filter_location (optional)
     * @param  string|null $car_filter_search (optional)
     * @param  string|null $car_filter_sort (optional)
     * @param  int|null $paged_query_page (optional)
     * @param  int|null $paged_query_page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\models\CarDto[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiCarsGetWithHttpInfo($car_filter_brand = null, $car_filter_type = null, $car_filter_capacity = null, $car_filter_fuel_type = null, $car_filter_gearbox = null, $car_filter_min_price = null, $car_filter_max_price = null, $car_filter_rating = null, $car_filter_location = null, $car_filter_search = null, $car_filter_sort = null, $paged_query_page = null, $paged_query_page_size = null, string $contentType = self::contentTypes['apiCarsGet'][0])
    {
        $request = $this->apiCarsGetRequest($car_filter_brand, $car_filter_type, $car_filter_capacity, $car_filter_fuel_type, $car_filter_gearbox, $car_filter_min_price, $car_filter_max_price, $car_filter_rating, $car_filter_location, $car_filter_search, $car_filter_sort, $paged_query_page, $paged_query_page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\CarDto[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\models\CarDto[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\CarDto[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiCarsGetAsync
     *
     * @param  string|null $car_filter_brand (optional)
     * @param  string|null $car_filter_type (optional)
     * @param  int|null $car_filter_capacity (optional)
     * @param  string|null $car_filter_fuel_type (optional)
     * @param  string|null $car_filter_gearbox (optional)
     * @param  float|null $car_filter_min_price (optional)
     * @param  float|null $car_filter_max_price (optional)
     * @param  int|null $car_filter_rating (optional)
     * @param  string|null $car_filter_location (optional)
     * @param  string|null $car_filter_search (optional)
     * @param  string|null $car_filter_sort (optional)
     * @param  int|null $paged_query_page (optional)
     * @param  int|null $paged_query_page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsGetAsync($car_filter_brand = null, $car_filter_type = null, $car_filter_capacity = null, $car_filter_fuel_type = null, $car_filter_gearbox = null, $car_filter_min_price = null, $car_filter_max_price = null, $car_filter_rating = null, $car_filter_location = null, $car_filter_search = null, $car_filter_sort = null, $paged_query_page = null, $paged_query_page_size = null, string $contentType = self::contentTypes['apiCarsGet'][0])
    {
        return $this->apiCarsGetAsyncWithHttpInfo($car_filter_brand, $car_filter_type, $car_filter_capacity, $car_filter_fuel_type, $car_filter_gearbox, $car_filter_min_price, $car_filter_max_price, $car_filter_rating, $car_filter_location, $car_filter_search, $car_filter_sort, $paged_query_page, $paged_query_page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiCarsGetAsyncWithHttpInfo
     *
     * @param  string|null $car_filter_brand (optional)
     * @param  string|null $car_filter_type (optional)
     * @param  int|null $car_filter_capacity (optional)
     * @param  string|null $car_filter_fuel_type (optional)
     * @param  string|null $car_filter_gearbox (optional)
     * @param  float|null $car_filter_min_price (optional)
     * @param  float|null $car_filter_max_price (optional)
     * @param  int|null $car_filter_rating (optional)
     * @param  string|null $car_filter_location (optional)
     * @param  string|null $car_filter_search (optional)
     * @param  string|null $car_filter_sort (optional)
     * @param  int|null $paged_query_page (optional)
     * @param  int|null $paged_query_page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsGetAsyncWithHttpInfo($car_filter_brand = null, $car_filter_type = null, $car_filter_capacity = null, $car_filter_fuel_type = null, $car_filter_gearbox = null, $car_filter_min_price = null, $car_filter_max_price = null, $car_filter_rating = null, $car_filter_location = null, $car_filter_search = null, $car_filter_sort = null, $paged_query_page = null, $paged_query_page_size = null, string $contentType = self::contentTypes['apiCarsGet'][0])
    {
        $returnType = '\OpenAPI\Client\models\CarDto[]';
        $request = $this->apiCarsGetRequest($car_filter_brand, $car_filter_type, $car_filter_capacity, $car_filter_fuel_type, $car_filter_gearbox, $car_filter_min_price, $car_filter_max_price, $car_filter_rating, $car_filter_location, $car_filter_search, $car_filter_sort, $paged_query_page, $paged_query_page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiCarsGet'
     *
     * @param  string|null $car_filter_brand (optional)
     * @param  string|null $car_filter_type (optional)
     * @param  int|null $car_filter_capacity (optional)
     * @param  string|null $car_filter_fuel_type (optional)
     * @param  string|null $car_filter_gearbox (optional)
     * @param  float|null $car_filter_min_price (optional)
     * @param  float|null $car_filter_max_price (optional)
     * @param  int|null $car_filter_rating (optional)
     * @param  string|null $car_filter_location (optional)
     * @param  string|null $car_filter_search (optional)
     * @param  string|null $car_filter_sort (optional)
     * @param  int|null $paged_query_page (optional)
     * @param  int|null $paged_query_page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiCarsGetRequest($car_filter_brand = null, $car_filter_type = null, $car_filter_capacity = null, $car_filter_fuel_type = null, $car_filter_gearbox = null, $car_filter_min_price = null, $car_filter_max_price = null, $car_filter_rating = null, $car_filter_location = null, $car_filter_search = null, $car_filter_sort = null, $paged_query_page = null, $paged_query_page_size = null, string $contentType = self::contentTypes['apiCarsGet'][0])
    {
        $resourcePath = '/api/cars';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_brand,
            'carFilter.Brand', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_type,
            'carFilter.Type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_capacity,
            'carFilter.Capacity', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_fuel_type,
            'carFilter.FuelType', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_gearbox,
            'carFilter.Gearbox', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_min_price,
            'carFilter.MinPrice', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_max_price,
            'carFilter.MaxPrice', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_rating,
            'carFilter.Rating', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_location,
            'carFilter.Location', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_search,
            'carFilter.Search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_filter_sort,
            'carFilter.Sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $paged_query_page,
            'pagedQuery.Page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $paged_query_page_size,
            'pagedQuery.PageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiCarsIdGet
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\models\CarDetailDto
     */
    public function apiCarsIdGet($id, string $contentType = self::contentTypes['apiCarsIdGet'][0])
    {
        list($response) = $this->apiCarsIdGetWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation apiCarsIdGetWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\models\CarDetailDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiCarsIdGetWithHttpInfo($id, string $contentType = self::contentTypes['apiCarsIdGet'][0])
    {
        $request = $this->apiCarsIdGetRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\CarDetailDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\models\CarDetailDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\CarDetailDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiCarsIdGetAsync
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsIdGetAsync($id, string $contentType = self::contentTypes['apiCarsIdGet'][0])
    {
        return $this->apiCarsIdGetAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiCarsIdGetAsyncWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsIdGetAsyncWithHttpInfo($id, string $contentType = self::contentTypes['apiCarsIdGet'][0])
    {
        $returnType = '\OpenAPI\Client\models\CarDetailDto';
        $request = $this->apiCarsIdGetRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiCarsIdGet'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiCarsIdGetRequest($id, string $contentType = self::contentTypes['apiCarsIdGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiCarsIdGet'
            );
        }


        $resourcePath = '/api/cars/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiCarsIdReviewsGet
     *
     * @param  string $id id (required)
     * @param  string|null $car_id car_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdReviewsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\models\ReviewDto[]
     */
    public function apiCarsIdReviewsGet($id, $car_id = null, string $contentType = self::contentTypes['apiCarsIdReviewsGet'][0])
    {
        list($response) = $this->apiCarsIdReviewsGetWithHttpInfo($id, $car_id, $contentType);
        return $response;
    }

    /**
     * Operation apiCarsIdReviewsGetWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string|null $car_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdReviewsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\models\ReviewDto[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiCarsIdReviewsGetWithHttpInfo($id, $car_id = null, string $contentType = self::contentTypes['apiCarsIdReviewsGet'][0])
    {
        $request = $this->apiCarsIdReviewsGetRequest($id, $car_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\models\ReviewDto[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\models\ReviewDto[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\models\ReviewDto[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiCarsIdReviewsGetAsync
     *
     * @param  string $id (required)
     * @param  string|null $car_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdReviewsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsIdReviewsGetAsync($id, $car_id = null, string $contentType = self::contentTypes['apiCarsIdReviewsGet'][0])
    {
        return $this->apiCarsIdReviewsGetAsyncWithHttpInfo($id, $car_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiCarsIdReviewsGetAsyncWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string|null $car_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdReviewsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiCarsIdReviewsGetAsyncWithHttpInfo($id, $car_id = null, string $contentType = self::contentTypes['apiCarsIdReviewsGet'][0])
    {
        $returnType = '\OpenAPI\Client\models\ReviewDto[]';
        $request = $this->apiCarsIdReviewsGetRequest($id, $car_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiCarsIdReviewsGet'
     *
     * @param  string $id (required)
     * @param  string|null $car_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiCarsIdReviewsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiCarsIdReviewsGetRequest($id, $car_id = null, string $contentType = self::contentTypes['apiCarsIdReviewsGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiCarsIdReviewsGet'
            );
        }



        $resourcePath = '/api/cars/{id}/reviews';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $car_id,
            'carId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
