volumes:
  db_data:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: wp-nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:cached
      - ./morent-wp:/var/www/html/wp-content/plugins/morent-wp
      - ./wp-config.php:/var/www/html/wp-config.php
  mysql:
    image: mysql:latest
    container_name: wp-mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  php:
    container_name: wp-php
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./wordpress:/var/www/html:cached
      - ./morent-wp:/var/www/html/wp-content/plugins/morent-wp
      - ./wp-config.php:/var/www/html/wp-config.php