<?php
/**
 * CreateRentalRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Morent.WebApi | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\models;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CreateRentalRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateRentalRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateRentalRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'car_id' => 'string',
        'pickup_date' => '\DateTime',
        'dropoff_date' => '\DateTime',
        'pickup_location' => '\OpenAPI\Client\models\CarLocationDto',
        'dropoff_location' => '\OpenAPI\Client\models\CarLocationDto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'car_id' => 'uuid',
        'pickup_date' => 'date-time',
        'dropoff_date' => 'date-time',
        'pickup_location' => null,
        'dropoff_location' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'car_id' => false,
        'pickup_date' => false,
        'dropoff_date' => false,
        'pickup_location' => false,
        'dropoff_location' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'car_id' => 'carId',
        'pickup_date' => 'pickupDate',
        'dropoff_date' => 'dropoffDate',
        'pickup_location' => 'pickupLocation',
        'dropoff_location' => 'dropoffLocation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'car_id' => 'setCarId',
        'pickup_date' => 'setPickupDate',
        'dropoff_date' => 'setDropoffDate',
        'pickup_location' => 'setPickupLocation',
        'dropoff_location' => 'setDropoffLocation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'car_id' => 'getCarId',
        'pickup_date' => 'getPickupDate',
        'dropoff_date' => 'getDropoffDate',
        'pickup_location' => 'getPickupLocation',
        'dropoff_location' => 'getDropoffLocation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('car_id', $data ?? [], null);
        $this->setIfExists('pickup_date', $data ?? [], null);
        $this->setIfExists('dropoff_date', $data ?? [], null);
        $this->setIfExists('pickup_location', $data ?? [], null);
        $this->setIfExists('dropoff_location', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['car_id'] === null) {
            $invalidProperties[] = "'car_id' can't be null";
        }
        if ($this->container['pickup_date'] === null) {
            $invalidProperties[] = "'pickup_date' can't be null";
        }
        if ($this->container['dropoff_date'] === null) {
            $invalidProperties[] = "'dropoff_date' can't be null";
        }
        if ($this->container['pickup_location'] === null) {
            $invalidProperties[] = "'pickup_location' can't be null";
        }
        if ($this->container['dropoff_location'] === null) {
            $invalidProperties[] = "'dropoff_location' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets car_id
     *
     * @return string
     */
    public function getCarId()
    {
        return $this->container['car_id'];
    }

    /**
     * Sets car_id
     *
     * @param string $car_id car_id
     *
     * @return self
     */
    public function setCarId($car_id)
    {
        if (is_null($car_id)) {
            throw new \InvalidArgumentException('non-nullable car_id cannot be null');
        }
        $this->container['car_id'] = $car_id;

        return $this;
    }

    /**
     * Gets pickup_date
     *
     * @return \DateTime
     */
    public function getPickupDate()
    {
        return $this->container['pickup_date'];
    }

    /**
     * Sets pickup_date
     *
     * @param \DateTime $pickup_date pickup_date
     *
     * @return self
     */
    public function setPickupDate($pickup_date)
    {
        if (is_null($pickup_date)) {
            throw new \InvalidArgumentException('non-nullable pickup_date cannot be null');
        }
        $this->container['pickup_date'] = $pickup_date;

        return $this;
    }

    /**
     * Gets dropoff_date
     *
     * @return \DateTime
     */
    public function getDropoffDate()
    {
        return $this->container['dropoff_date'];
    }

    /**
     * Sets dropoff_date
     *
     * @param \DateTime $dropoff_date dropoff_date
     *
     * @return self
     */
    public function setDropoffDate($dropoff_date)
    {
        if (is_null($dropoff_date)) {
            throw new \InvalidArgumentException('non-nullable dropoff_date cannot be null');
        }
        $this->container['dropoff_date'] = $dropoff_date;

        return $this;
    }

    /**
     * Gets pickup_location
     *
     * @return \OpenAPI\Client\models\CarLocationDto
     */
    public function getPickupLocation()
    {
        return $this->container['pickup_location'];
    }

    /**
     * Sets pickup_location
     *
     * @param \OpenAPI\Client\models\CarLocationDto $pickup_location pickup_location
     *
     * @return self
     */
    public function setPickupLocation($pickup_location)
    {
        if (is_null($pickup_location)) {
            throw new \InvalidArgumentException('non-nullable pickup_location cannot be null');
        }
        $this->container['pickup_location'] = $pickup_location;

        return $this;
    }

    /**
     * Gets dropoff_location
     *
     * @return \OpenAPI\Client\models\CarLocationDto
     */
    public function getDropoffLocation()
    {
        return $this->container['dropoff_location'];
    }

    /**
     * Sets dropoff_location
     *
     * @param \OpenAPI\Client\models\CarLocationDto $dropoff_location dropoff_location
     *
     * @return self
     */
    public function setDropoffLocation($dropoff_location)
    {
        if (is_null($dropoff_location)) {
            throw new \InvalidArgumentException('non-nullable dropoff_location cannot be null');
        }
        $this->container['dropoff_location'] = $dropoff_location;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


